coursework/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('homeapp.urls')),
    path('teams/', include('teams.urls')),
    path('admin/', admin.site.urls),
]

teams/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.teams, name='teams'),
    path('fixtures', views.fixtures, name='fixtures'),
    path('table', views.table, name='table'),
    path('create', views.create, name='create'),
    path('register_fixture', views.register_fixture, name = 'register_fixture'),
]
#settings for image upload
urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

teams/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError


#Team model
class team(models.Model):
    name = models.CharField(max_length=100, unique=True)
    player_count = models.IntegerField(validators = [MinValueValidator(11)])
    year_founded = models.IntegerField(validators = [MaxValueValidator(2022)])
    owner_email = models.EmailField(max_length=100)
    image = models.ImageField(null=True, blank=True, upload_to='images/')

#Fixture model which is to be plated with 2 teams
class fixtures(models.Model):
    #Makes sure that only 1 pair of team1 and team2 can exist
    class Meta:
        unique_together = ['team1', 'team2']
    team1 = models.ForeignKey(team, on_delete=models.CASCADE, related_name='team1')
    team2 = models.ForeignKey(team, on_delete=models.CASCADE, related_name='team2')
    score1 = models.IntegerField(default=0)
    score2 = models.IntegerField(default=0)

#Table model which is composed of many teams
class table(models.Model):
    team = models.ForeignKey(team, on_delete=models.CASCADE)
    score = models.IntegerField(default=0)
    wins = models.IntegerField(default=0)
    draws = models.IntegerField(default=0)
    loses = models.IntegerField(default=0)
    GP = models.IntegerField(default=0)
    GF = models.IntegerField(default=0)
    GA = models.IntegerField(default=0)

teams/forms.py
from django import forms
from .models import team, fixtures
# creating a form
class teamForm(forms.ModelForm):
    # create meta class
    class Meta:
        # specify model to be used
        model = team
        #Form fields corresponding to the model attributes
        fields = ['name', 'player_count', 'year_founded', 'owner_email', 'image']
        widgets = {
        'name': forms.TextInput(attrs={
        'class': 'formfield',
        'placeholder': 'Team Name',
        }),
        'player_count': forms.NumberInput(attrs={
        'class': 'formfield',
        'placeholder': 'Player Count',
        }),
        'year_founded': forms.NumberInput(attrs={
        'class': 'formfield',
        'placeholder': 'Year Founded',
        }),
        'owner_email': forms.TextInput(attrs={
        'class': 'formfield',
        'placeholder': 'Owner Email',
        }),
    }

class fixtureForm(forms.ModelForm):
     class Meta:
        # specify model to be used
        model = fixtures
        #Form fields corresponding to the model attributes
        fields = ['team1', 'team2', 'score1', 'score2']
        widgets = {
        'team1': forms.NumberInput(attrs={
        'class': 'formfield',
        'placeholder': 'Team1 ID',
        }),
        'team2': forms.NumberInput(attrs={
        'class': 'formfield',
        'placeholder': 'Team2 ID',
        }),
        'score1': forms.NumberInput(attrs={
        'class': 'formfield',
        'placeholder': 'Team1 Score',
        }),
        'score2': forms.NumberInput(attrs={
        'class': 'formfield',
        'placeholder': 'Team2 Score',
        }),
    }

teams/views.py
from django.shortcuts import (get_object_or_404, render, redirect)
from django.contrib import messages
from .models import team, table as tablemodel, fixtures as fixturesmodel
from .forms import teamForm, fixtureForm


#Returns all fixtures by descending ID, so most recent ones on top
def fixtures(request):
    context = {}
    context['fixtures_list'] = fixturesmodel.objects.all().order_by('-id')
    context["team_list"] = team.objects.all()
    return render(request, 'teams/fixtures.html', context)

#Returns the table with descending team points
def table(request):
    context = {}
    context["table_list"] = tablemodel.objects.all().order_by('-score')
    context["team_list"] = team.objects.all()
    #Updates the table model to make sure it includes all the teams
    for teamobj in team.objects.all():
        if (not tablemodel.objects.filter(team_id=teamobj.id).exists()):
            a = tablemodel.objects.create(team_id=teamobj.id)
            a.save()
    return render(request, 'teams/table.html', context)

#Retruns a list of all teams
def teams(request):
    context = {}
    context["team_list"] = team.objects.all()
    return render(request, "teams/teams.html",context)

#Dealing with fixture registration form
def register_fixture(request):
    context = {}
    form = fixtureForm(request.POST or None)
    if (request.method == 'POST'):
        if form.is_valid():
            #Save the form data to variables which are used to update the table database
            team1ID = form.cleaned_data['team1']
            team2ID = form.cleaned_data['team2']
            score1 = form.cleaned_data['score1']
            score2 = form.cleaned_data['score2']
            team1 = tablemodel.objects.get(team_id=team1ID)
            team2 = tablemodel.objects.get(team_id=team2ID)
            #Add 1 to both team's games played
            team1.GP += 1
            team2.GP += 1
            #Add the corresponding goals to their total goals scored
            team1.GF += score1
            team1.GA += score2
            team2.GF += score2
            team2.GA += score1
            #Gives the teams points depending on if they win, lose, or tie
            if score1 > score2:
                team1.wins += 1
                team2.loses += 1
                team1.score += 3
            elif score2 > score1:
                team1.loses += 1
                team2.wins += 1
                team2.score += 3
            else:
                team1.draws +=1
                team2.draws += 1
                team1.score += 1
                team2. score += 1
            #Save the data to database
            team1.save()
            team2.save()
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Fixture Registered')
            return redirect('fixtures')
    context['form']= form
    context["team_list"] = team.objects.all()
    return render(request, "teams/register_fixture.html",context)

#Deals with team creation form
def create(request):
    context ={}
    form = teamForm(request.POST or None)
    if(request.method == 'POST'):
        form = teamForm(request.POST, request.FILES)
        #If form is valid, then save the data to teams database and display success message
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS, 'Team Registered')
            return redirect('table')
        #Otherwise display error message
        else:
            messages.add_message(request, messages.ERROR, 'Invalid Form Data; Team not registered')
    context['form']= form
    return render(request, "teams/create.html", context)

teams/templates/teams/create.html
{% extends "base.html" %}
{% block content %}
<script>
    //Checks if form is valid
function validateForm() {
    //Checks if user has agreed to terms and conditions
    if (!$("#agreeToTerms").is(':checked')) {
        window.alert("Please checek terms and conidtions");
        return false;
    }
    //Checks if player count is higher than 26
    if ($("#id_player_count").val() > 26) {
        window.alert("Player count too high");
        return false;
    }
    return true;
}
</script>
<h1>Register your team here</h1>
<form method="POST" enctype="multipart/form-data" onsubmit="return validateForm()" >
    <!-- Security token -->
    {% csrf_token %}
    <!-- Using the formset -->
    {{ form.as_p }}
    I agree to the terms and conditions<input type="checkbox" id="agreeToTerms">
    <br>
    <input type="submit" id ="submit" value="Submit">
{% endblock content %} 

teams/templates/teams/fixtures.html
{% extends "base.html" %}
{% block title %}
<title>Fixtures </title>
{% endblock title%}
{% block content %}
<table>
    <tr>
        <th>Team Name</th>
        <th colspan=2>Score</th>
        <th>Team Name</th>
    </tr>
    {% for game in fixtures_list %}
        
        <tr>
            <td>
            {% for team in team_list %}
                {% if team.id == game.team1_id %}
                    {{ team.name }}
                {% endif %}
            {% endfor %}
            </td>
            <td>
                {{ game.score1}}
            </td>
            <td>
                {{game.score2}}
            </td>
            <td>
                {% for team in team_list %}
                    {% if team.id == game.team2_id %}
                        {{ team.name }}
                    {% endif %}
                {% endfor %}
            </td>
        </tr>
    {% endfor %}
   </table> <hr/>

{% endblock content %} 

teams/templates/teams/register_fixture.html
{% extends "base.html" %}
{% block title %}
<title>Register fixture </title>
{% endblock title%}
{% block content %}
<script>
    //Validates form submission
function validateForm() {
    //Checks if user submitted negative amounts of goals
    if ($("#id_score1").val() < 0 || $("#id_score2").val() < 0) {
        window.alert("Please input a valid score");
        return false;
    }
    //Checks if user put the same team for team1 and team2
    if ($("#id_team1").val() == $("#id_team2").val()) {
        window.alert("Teams cannot be the same");
        return false;
    }
}

</script>
<h1>Register your fixture here</h1>
<form method="POST" enctype="multipart/form-data" id="fixturesForm" onsubmit= "return validateForm()">
    <!-- Security token -->
    {% csrf_token %}
    <!-- Using the formset -->
    {{ form.as_p }}
    <input type="submit" id ="submit" value="Submit">
{% endblock content %} 

teams/templates/teams/table.html
{% extends "base.html" %}
{% block title %}
<title>Table</title>
{% endblock title%}
{% block content %}
<table>
    <tr>
        <th>Team ID</th>
        <th>Name</th>
        <th>Points</th>
        <th>Wins</th>
        <th>Draws</th>
        <th>Losses</th>
        <th>GP</th>
        <th>GF</th>
        <th>GA</th>
    </tr>
    {% for team in table_list %}
        
        <tr>
            <td>
                {{ team.team_id }}
            </td>
            <td>
            {% for team2 in team_list %}
                {% if team2.id == team.team_id %}
                    {{ team2.name }}
                {% endif %}
            {% endfor %}
            </td>
            <td>
                {{ team.score}}
            </td>
            <td>
                {{team.wins}}
            </td>
            <td>
                {{team.draws}}
            </td>
            <td>
                {{ team.loses | truncatechars:20}}
            </td>
            <td>
                {{ team.GP}}
            </td>
            <td>
                {{team.GF}}
            </td>
            <td>
                {{team.GA}}
            </td>
        </tr>
    {% endfor %}
   </table> <hr/>
{% endblock content %} 

teams/templates/teams/teams.html
{% extends "base.html" %}
{% block title %}
<title>Teams </title>
{% endblock title%}
{% block content %}
<table>
    <tr>
        <th>Team Logo</th>
        <th>Team ID</th>
        <th>Name</th>
        <th>Player Count</th>
        <th>Year Founded</th>
        <th>Owner Email</th>
    </tr>
    {% for team in team_list %}
        <tr>
            <td>
                <!--Checks if the team has a corresponding logo in the database-->
                {% if team.image %}
                <img src="static{{ team.image.url}}"width=100px>
                {% else %}
                <!--Otherwise use default football logo-->
                <img src="static/images/football_icon.jpg"width=50px>
                {% endif %}
            <td>
                {{ team.id }}
            </td>
            <td>
                {{ team.name | truncatechars:20}}
            </td>
            <td>
                {{ team.player_count}}
            </td>
            <td>
                {{team.year_founded}}
            </td>
            <td>
                {{team.owner_email}}
            </td>
        </tr>
    {% endfor %}
   </table> <hr/>
{% endblock content %} 